# Generated by Django 5.1 on 2024-09-28 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('employee_type', models.CharField(blank=True, choices=[('full_time', 'full_time'), ('part_time', 'Part_time'), ('contact', 'contact'), ('internship', 'Internship'), ('temporary', 'Temporary')], max_length=100, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('application_dateline', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
