# Generated by Django 5.1 on 2024-09-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_jobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
