# Generated by Django 5.1 on 2024-09-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_jobmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full_time'), ('part_time', 'Part_time'), ('contact', 'Contact'), ('internship', 'Internship'), ('temporary', 'Temporary')], max_length=100, null=True),
        ),
    ]
