# Generated by Django 5.1 on 2024-09-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_jobmodel_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
