# Generated by Django 5.1 on 2024-09-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_jobmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('jobseeker', 'Jobseeker')], max_length=100, null=True),
        ),
    ]
