# Generated by Django 5.1 on 2024-09-29 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobApplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume', models.FileField(blank=True, max_length=200, null=True, upload_to='Media/Resume')),
                ('Cover_letter', models.TextField(blank=True, null=True)),
                ('Full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Work_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('Skill', models.CharField(blank=True, max_length=100, null=True)),
                ('Linkedin_URL', models.URLField(blank=True, max_length=100, null=True)),
                ('Expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.jobmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
